---
driver:
  name: docker
  hostname: watchdog.ci.local
  #socket: tcp://127.0.0.1:2376
  use_sudo: false



provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  formula: watchdog
  log_level: info
  state_top:
    base:
      "*":
        - watchdog
  pillars:
    top.sls:
      base:
        "*":
          - watchdog
  grains:
    noservices: True


platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.1


verifier:
  name: inspec
  sudo: true


suites:
  - name: default
  #  provisioner:
  #    pillars-from-files:
  #      watchdog.sls: tests/pillar/default.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
